runtime: python312 
# Substitua "SEUPROJETO" pelo nome do seu projeto Django (o mesmo nome da pasta que tem o arquivo settings.py)
entrypoint: gunicorn -b :$PORT pw2026.wsgi 


handlers:
- url: /static
  static_dir: static_gcloud/
- url: /.*
  script: auto

automatic_scaling:
  min_instances: 0
  max_instances: 2